spring:
  application:
    name: tutorial

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  mybatis:
    mapper-locations:
      - classpath:mybatis-mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: null

  h2:
    console:
      enabled: true
      path: /h2-console

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

